# Generated by Django 2.1.3 on 2018-11-28 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participantes.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=100, verbose_name='CURP')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('sexo', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=20, verbose_name='Telefono')),
                ('ocupacion', models.CharField(max_length=20, verbose_name='Telefono')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='participantes', verbose_name='Foto')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participantes.Estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participantes.Municipio')),
            ],
        ),
    ]
