# Generated by Django 2.1.3 on 2018-11-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='sexo',
        ),
    ]
