# Generated by Django 2.1.3 on 2018-11-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0002_remove_participante_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='correo',
            field=models.CharField(max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='ocupacion',
            field=models.CharField(max_length=100, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
