# Generated by Django 2.1.3 on 2018-11-29 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participantes', '0003_auto_20181128_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=150, verbose_name='Nombre')),
                ('participante_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante_1', to='participantes.Participante')),
                ('participante_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante_2', to='participantes.Participante')),
                ('participante_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante_3', to='participantes.Participante')),
                ('participante_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante_4', to='participantes.Participante')),
            ],
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical', models.CharField(max_length=100, verbose_name='Vertical')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='vertical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.Vertical'),
        ),
    ]
